### ISSUE TITLE
How to handle constraints errors? 

### ISSUE THREAD

**Issue by bmelton** [synw/sqlview#1]
BatchInsert allows for use of ConflictAlgorithm.replace / ignore / whatever, but I don't see any implementation for this on the regular db.insert method, and can't figure out how to handle those errors. Should I just `try` and `catch` them, or is there something obvious that I'm missing?

**Comment by synw** [comment]
I moved this issue to the Sqlcool repository: https://github.com/synw/sqlcool/issues/14 because this question is handled by this lib. I answered there

**Comment by bmelton** [comment]
Apologies. I must have gotten turned around somewhere. Thanks!
